---
title: "L01 Review"
subtitle: "Data Science 3 with R (STAT 301-3)"
author: "Sophia Fresquez"
pagetitle: "L01 Sophia Fresquez"
date: today

format:
  html:
    theme: cosmo
    toc: true
    toc-depth: 4
    toc-location: left
    embed-resources: true
    code-fold: false
    link-external-newwindow: true

execute:
  warning: false

from: markdown+emoji
reference-location: margin
citation-location: margin   
---

::: {.callout-tip icon="false"}
## Github Repo Link

[L01 Review (sophiafresquez-2)](https://github.com/stat301-3-2026-spring/l01-review-sophiafresquez-2.git)
:::

## Overview

The goal of this lab is to review machine learning/predictive modeling vocabulary and concepts covered in Data Science 2 with R (STAT 301-2).

## Questions

When completing the following questions ensure your solutions are neatly formatted and clearly indicated. Consider including diagrams/images in some of your solutions, if it helps to make things easier to describe/discuss.

### Question 1

Provide a brief outline/overview of the steps involved in a supervised machine learning process. Could provide this as a bulleted list. 

::: {.callout-tip icon="false"}
## Solution

- Split data into test/train/validation
- Define feature engineering and model type
- Train model
- Make predictions
- Evaluate results

:::

### Question 2

Last quarter we had an introduction to supervised machine learning processes. Supervised machine learning involves making predictions of a target variable then comparing this prediction the true observation in order to evaluate performance. We have a outcome that supervises/guides the process and this is what we use to make choices about which model is better for a given task.

You do not have a target of interest/an outcome variable in unsupervised learning. What we do have is a dataset where we want to understand the structure between the different observations. 

::: {.callout-tip icon="false"}
## Solution

Last quarter we had an introduction to supervised machine learning processes. Supervised machine learning involves making predictions, and importantly, having a true observation to compare each value to in order to evaluate performance. 

:::

### Question 3 

In general, we can classify a model by its purpose into 1 of the 3 categories below. Provide a brief description of the goals of these model classes.

#### Descriptive Models 

::: {.callout-tip icon="false"}
## Solution

A descriptive model demonstrates the important features and/or patterns of a dataset. The goal is to show what happened, but not to explain the reasons behind the trends or make predictions.

:::

#### Inferential Models

::: {.callout-tip icon="false"}
## Solution

Inferential models aim to explain the how of relationships. They are used to test and estimate relationships in data to determine whether they are statistically significant and/or generalizable to a larger population.

:::

#### Predictive Models

::: {.callout-tip icon="false"}
## Solution

The real goal of predictive models is not to understand the underlying reasoning, but just to make accurate predictions. We don't have to understand why, in fact sometimes we include parameters that have no affect and that's okay, the goal is just to minimize error. 

:::

### Question 4 

We can further describe/classify predictive models by how they were derived or developed as being either mechanistic or empirically driven. 

#### Part (a)

What does it mean to be a mechanistic model?

::: {.callout-tip icon="false"}
## Solution

Parametric models are explainable models made with assumptions. The main foundation of these models is done by the assumptions and not the data. For example, linear models are mechanistic the huge assumption being that the underlying function is linear. 
However, if the assumptions aren't met the model will most likely be a bad fit, but if they are, the model is most likely going to be very efficient.  

:::

#### Part (b)

What does it mean to be an empirically driven model?

::: {.callout-tip icon="false"}
## Solution

Empirically driven model are data driven models. We make few or no assumptions about the structure of the data. Instead, the model will assess the data and make choices about the best fitting patterns accordingly. 

:::

#### Part (c)

How does the mechanistic and empirically driven model terminology relate to the parametric and nonparametric model terminology? 

::: {.callout-tip icon="false"}
## Solution

A mechanistic vs an empirically driven model describes how the model is built, either rooted in theory or learned from data. A parametric vs a nonparametric model describes how flexible the model is in representing relationships, whether is has freedom in how to calculate relationships or if it only adjusts a fixed number of parameters as best it can. 

:::

#### Part (d)

In general, is a mechanistic or empirically driven model easier to interpret? Explain.

::: {.callout-tip icon="false"}
## Solution

I think a mechanistic model is easier to interpret since they are made based on known theory or processes. This means that each part of the model has a clear interpretation as opposed to an empirically driven model where choices are just made to optimize performance and not due to prior knowledge. 

:::

#### Part (e)

How does mechanistic and empirically driven model terminology relate to the idea of model flexibility? That is, which would be more or less flexible than the other.

::: {.callout-tip icon="false"}
## Solution

An empirically driven model would be more flexible since we let the data determine the form of the relationship which is quite flexible. On the other hand, mechanistic models are built from theory meaning their structure is fixed in advance. 

:::

#### Part (f)

Describe the bias-variance trade-off when considering the use of a mechanistic or empirically driven model. 

::: {.callout-tip icon="false"}
## Solution

Mechanistic models tend to have higher bias and lower variance since they are constrained by theory they can oversimplify reality (higher bias). However, they are less sensitive to changes in the data (lower variance).  
Empirically driven models tend to have lower bias and higher variance since they can fit complex patterns (lower bias). However, this leaves them prone to over fitting which makes them more sensitive to noise (higher variance).

:::

### Question 5 

Explain the difference between a regression and classification machine learning (ML) problems.

::: {.callout-tip icon="false"}
## Solution

A regression problem predicts a numerical value as the outcome variable while a classification problem predicts a label/factor. 

:::

### Question 6 

When splitting the data, why is it useful to stratify by the outcome/target variable? 

::: {.callout-tip icon="false"}
## Solution

It's pretty much always a good idea to stratify by the outcome variable to ensure that there is even representation of all ranges of the outcome variable values in each fold. If you don't stratify, this can create class imbalances or skews that are not present in the dataset as a whole. 

:::

### Question 7 

Briefly describe how v-fold cross validation with repeats is used to estimate test RMSE. Also provide an explanation of why we use it. 

::: {.callout-tip icon="false"}
## Solution

V-fold cross validation with repeats splits the data into $v$ folds and trains the model on $v-1$ folds and evaluates it on the last fold. This process is then repeated until each fold has been the validation set once and the RMSE calculated from each evaluation is averaged together to get this split's RMSE.  
Then, this entire process is then repeated multiple times with different random splits and all RMSE results are averaged to produce a more stable estimate by reducing the impact of any single random split. 

:::

### Question 8

When might we use a bootstrap resampling procedure instead of v-fold cross validation to estimate test RMSE?

::: {.callout-tip icon="false"}
## Solution

You should use bootstrap when the dataset is small since with bootstrap each resample is the same size as the original train set, but with v-fold cross-validation the resamples are $1/v^{th}$ the size of the train set. 

:::

### Question 9 

Briefly describe model tuning and why we use it.

::: {.callout-tip icon="false"}
## Solution

We tune model hyperparameters to find the optimal values over the ranges we search. This process helps identify the best values since we don’t know them ahead of time.
:::

### Question 10 

What are two common performance metrics when dealing with a regression ML problem?

::: {.callout-tip icon="false"}
## Solution

RMSE  
$R^2$

:::

What are two common performance metrics when dealing with a classification ML problem?

::: {.callout-tip icon="false"}
## Solution

Accuracy  
ROC AUC

:::

### Question 11

Classify each question/problem below as either prediction or inferential. Explain your reasoning for each.

A company with a subscription based service (for example Netflix, Disney+, New York Times, etc) has data concerning customer interactions with a them, including features like the number of customer service calls, quality of service calls, subscription length, engagement with the service, discounted service, etc. They are interested in two questions:

1. Does a high number of service calls impact a customer's likelihood of churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

This is an inferential since we are trying to understand the relationship between two variables and test whether it is significant. 

:::

2. How likely is it that a customer will churn in the next month (leave the company/drop the service)?

::: {.callout-tip icon="false"}
## Solution

This is a predictive problem because we are trying to forecast an outcome for the future. We don't need to understand why this occurs, we just want to make the best estimate we can. 

:::


